import matplotlib.pyplot as plt
import re
import os

dimensions = []
python_ms = []
c_ms = []
java_ms = []

# Automatically read the data generated by benchmark.py
results_path = 'results.md'

try:
    with open(results_path, 'r', encoding='utf-8') as f:
        for line in f:
            # Search for table rows: | NxN | py_time ± py_std | py_mem | c_time ± c_std | ...
            match = re.search(r'\|\s*(\d+)x\d+\s*\|\s*([\d\.]+)\s*±.*?\|\s*([\d\.]+)\s*±.*?\|\s*([\d\.]+)\s*±', line)
            if match:
                dimensions.append(int(match.group(1)))
                python_ms.append(float(match.group(2)))
                c_ms.append(float(match.group(3)))
                java_ms.append(float(match.group(4)))
                
except FileNotFoundError:
    print(f"Error: '{results_path}' not found. Run benchmark.py first.")
    exit(1)

if not dimensions:
    print("Error: Could not extract data from the table. Check the format of results.md.")
    exit(1)

# Generate the plot
plt.figure(figsize=(10, 6))
plt.plot(dimensions, python_ms, marker='o', label='Python', color='red', linewidth=2)
plt.plot(dimensions, c_ms, marker='s', label='C', color='blue', linewidth=2)
plt.plot(dimensions, java_ms, marker='^', label='Java', color='green', linewidth=2)

plt.title('Performance Comparison: $O(n^3)$ Matrix Multiplication', fontsize=14)
plt.xlabel('Matrix Dimension (N x N)', fontsize=12)
plt.ylabel('Execution Time (Median in ms)', fontsize=12)
plt.yscale('log')  # Logarithmic scale to appreciate the differences
plt.grid(True, which="both", ls="--", alpha=0.5)
plt.legend(fontsize=12)

plt.tight_layout()
plt.savefig('performance_graph.png', dpi=300)
print("Plot successfully saved as 'performance_graph.png'.")